### ISSUE TITLE
Document Issue / Number Generator / Views and Sheets

### ISSUE THREAD

**Issue by jgunstone** [maxfordham/document-issue#66]
```yaml
project_number: 4321
name: document-issue
work_types: 
  - "TB02"
project-drivers:
  - efficicency
  - quality
  - data-insights
director: KD
stakeholders:
  - EC
  - LH
  - AM
delivery: 
  - JG
  - OH
```

## Brief

- [ ] retire the Document Number Generator spreadsheet and replace with App
- [ ] store document issue data in a centralised database
- [ ] synchronise issue data with Revit sheets and views
- [ ] improve support in Revit for less standard drawing types: e.g. 
  - [ ] Add many views to 1 sheet tool
  - [ ] Automatic naming and numbering of strategy sheets?

## Description

The Document Number Generator in excel was made as a quick fix to a problem. It has served that aim well but is time-consuming to maintain and error-prone in operation.

The Revit Views and Sheets tools are the most powerful and heavily used automation tools delivered by the pyRevit toolbar, but in many circumstances they don't work. Keeping them up-to-date with changes to the Document Number Generation producedues and uniclass numbers etc. is very difficult. Keeping the list of drawings that exist in Revit up-to-date with the information in the DNG / issue sheet is manual and time-consuming. 

In addition the tools do not work for:
- less common drawings like details, drawings with multiple views or levels, combined service drawings...
- projects where there is any deviation from the the standard naming procedure
- projects where Revit isn't the only place drawings are being produced

## Optionals / For Consideration

- [ ] store archive of issued files (needs consideration w.r.t. Sharepoint, Autodesk Docs etc.) ?
- [ ] "internal issues" to support the design review process?
